version: '3.8'

services:
   db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=123qweWE
      ports:
         - "1433:1433"
      restart: unless-stopped

   api:
      build: .
      ports:
         - "5007:80"
      restart: unless-stopped
      depends_on:
         - db

   ui:
      build: ./src/Mc2.CrudTest.UI
      ports:
         - "5006:80"
      restart: unless-stopped
      depends_on:
         - api




