version: '3.8'

services:
   db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      user: ubuntu
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=123qweWE
      ports:
         - "1433:1433"
      volumes:
         - Mc2:/var/opt/mssql/data
      restart: unless-stopped

   api:
      user: ubuntu
      build: .
      volumes:
         - ./data/api:/data/
      ports:
         - "5007:80"
      restart: unless-stopped
      depends_on:
         - db

volumes:
   Mc2:


