@baseUrl=http://localhost:5087


GET {{baseUrl}}/api/customers
Content-Type: application/json


###
GET {{baseUrl}}/api/customers/13ded527-31a3-454c-b9b6-0dbe82318c37
Content-Type: application/json


###
POST {{baseUrl}}/api/customers
Content-Type: application/json

{
  "firstName": "nima",
  "lastName": "nosrat",
   "email": "nima@gmail.com",
   "phoneNumber":"09107602786",
   "bankAccountNumber":"1212121212121212",
   "DateOfBirth":"1990-01-01"
}