apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deploymentapi.name}}"
  app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: "{{ .Values.deploymentapi.name}}"
  ports:
  - name: http
    port: 5007
    targetPort: 80
  type: LoadBalancer
