apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deploymentapi.name}}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.deploymentapi.name}}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentapi.name}}"
    spec:
      containers:
      - name: "{{ .Values.deploymentapi.name}}"
        image: {{ .Values.deploymentapi.image }}:{{ .Values.deploymentapi.tag }}
        ports:
        - containerPort: 80
        env:
        - name:  ConnectionStrings__McTestContext
          value: "Server=db;Initial Catalog =McTestContext;MultipleActiveResultSets=true;User ID=sa;Password=123qweWE;Max Pool Size=1000;Pooling=true;Encrypt=False"
        - name: db
          value: "db"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi