apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deploymentdb.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.deploymentdb.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.deploymentdb.name }}"
    spec:
      containers:
      - name: "{{ .Values.deploymentdb.name }}"
        image: "{{ .Values.deploymentdb.image }}:{{ .Values.deploymentdb.tag }}}}"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "123qweWE"
        ports:
        - containerPort: 1433
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
