apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deploymentdb.name }}"
  app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: "{{ .Values.deploymentdb.name }}"
  ports:
  - name: "{{ .Values.deploymentdb.name }}"
    port: 1433
    targetPort: 1433
  type: ClusterIP
