apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploymentui.name}}"
spec:
  selector:
    matchLabels:
      app: "{{.Values.deploymentui.name}}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{.Values.deploymentui.name}}"
    spec:
      containers:
      - name: "{{.Values.deploymentui.name}}"
        image: "{{.Values.deploymentui.image}}"
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://ui-service:80"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
